spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: darcyxian
    password: darcyxian
    platform: postgresql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: darcy_database_create.sql