insert into menu (description,price,price2,category,special)
values
('Toast & Jam','8 ','','breakfast','0'),
('Mushrooms on Toast','18','','breakfast','0'),
('Tomato’s on Toast','15','','breakfast','0'),
('Muesli with Yogurt & Milk','15','','breakfast','0'),
('Bacon & Egg Roll with BBQ Sauce, Caramelized Onion & Cheese','18','','breakfast','0'),
('Banana, Bacon, Maple & Cheese on Toast','18','','breakfast','0'),
('Add Scrambled Eggs','5 ','','breakfast','0'),
('Bacon & Eggs served with Toast','18','','breakfast','0'),
('Mushroom Omelette served with Toast','22','','breakfast','0'),
('Ham & Tomato Omelette served with Toast','22','','breakfast','0'),
('Scrambled Eggs with Ham & Kranski served with Toast','24','','breakfast','0'),
('Veggie Breakfast – Haloumi, Mushrooms, Tomato, Eggplant & Poached Egg with Toast','25','','breakfast','0'),
('Eggs Benedict served on Turkish Toast with Ham or Salmon','26','','breakfast','0'),
('Locky Breakfast – Lamb Cutlet, Bacon, Mushroom, Tomato, Soft Scrambled Eggs,
Turkish Toast & Tomato Chutney','28','','breakfast','0'),
('Bootcamp Turkish Toast Avocado Salmon Scrambled Egg Fetta','26','','breakfast','0'),

('Blue Eye Croquettes','18','','lunch','0'),
('Duck Spring Rolls','24','','lunch','0'),
('Steak Burger & Chips','25','','lunch','0'),
('Chicken Burger & Chips','25','','lunch','0'),
('0/2 & 0/2 Burger & Chips','30','','lunch','0'),
('Fish & Chips Grilled or Battered','36','','lunch','0'),
('Creamy Garlic Prawns & Scallops','35','','lunch','0'),
('Pasta of the Day','30','','lunch','0'),
('Moroccan Spiced Lamb Salad','36','','lunch','0'),
('Crispy Chicken Caesar Salad','25','','lunch','0'),
('Thai Fish Cake Salad','24','','lunch','0'),
('Butchers Cut Steak','40','','lunch','0'),
('Turkish Bread Toasties','16','','lunch','0'),

('Pork Schnitzel with Plum Sauce, Chips and Salad','22','','lunch','1'),
('Mussels in Tomato,Basil, Coconut Cream with bread','36','','lunch','1'),
('House Baked Sausage Rolls with Chips and Salad','15','','lunch','1'),
('StirFried Mutton Bird Salad','25','','lunch','1'),

('Pork Schnitzel with Plum Sauce, Chips and Salad','22','','lunch','1'),
('Mussels in Tomato, Basil, Coconut Cream with Bread','36','','lunch','1'),
('House Baked Sausage Rolls with Chips and Salad','15','','lunch','1'),
('StirFried Mutton Bird Salad','25','','lunch','1'),

('Garlic or Herb Bread','9 ','','entrée','0'),
('Grilled Game Kransky with Red Peppers & Jalepeno Relish','18','','entrée','0'),
('Blue Eye Croquettes with Blue Cheese Sauce','18','','entrée','0'),
('Tassie Half Shell Scallops Rockefeller style, topped with Herb Butter, Bacon,
Panko Crumbs & Parmesan','34','','entrée','0'),
('House Rolled Duck Spring Rolls served with our famous Orange Sauce','24','','entrée','0'),
('Crispy Chicken served with Caesar Dipping Sauce','18','','entrée','0'),
('Thai Fish Cakes served with Sweet Chilli Dipping Sauce','22','','entrée','0'),
('Oysters Available','MP','','entrée','0'),

('Seasoned Grilled Fish of the Day served with Steamed Asian Greens & Croquette','38','','main','0'),
('Battered Fish & Chips served with Salad & Tartare','36','','main','0'),
('Creamy Garlic Prawns & Scallops served with Rice','35','','main','0'),
('Seafood Chicken – Chicken Fillet topped with Creamy Garlic Prawns& Scallops with
Rice & Salad','39','','main','0'),
('Moroccan Spiced Lamb Salad with Feta, Pepita & Sunflower seeds, Pumpkin & finished
with Cucumber Yoghurt','36','','main','0'),
('Slow Baked Four Quarter Lamb with Minted Mushy Peas, Carrots & Potato','35','','main','0'),
('Butchers Cut Steak cooked to your liking served with Chips, Salad or Vegetables & your
choice of Pepper Sauce or Sautéed Mushrooms','48','','main','0'),
('Pasta of the day','34','','main','0'),
('Chef’s Choice Vegan or Vegetarian Meals','Price Upon Request','','main','0'),

('Poached Ocean Trout in Chinese Master Stock with Steamed Greens and Rice','38','','dinner','1'),
('Mussels in Tomato, Basil, Coconut Cream with Bread','36','','dinner','1'),
('Pork Steak, Plum Sauce with Salad and Chips','35','','dinner','1'),
('FiletMignon','48','','dinner','1'),

('Chicken Pasta','18','','children','0'),
('Cheesy Pasta','12','','children','0'),
('Battered Fish, Chips & Salad','17','','children','0'),
('Grilled Fish, Chips & Salad','17','','children','0'),
('Grilled Chicken, Chips & Salad','18','','children','0'),
('Chicken Burger & Chips','18','','children','0'),
('Lamb cutlets, Chips & Salad','18','','children','0'),
('Steak, Chips & Salad','20','','children','0'),
('Crispy Chicken &Chips','22','','children','0'),

('Almond Cake G.F.','15','','desserts','1'),
('Sticky Date Pudding G.F.','15','','desserts','1'),
('Caramel Tart','15','','desserts','1'),
('Lemon Cheesecake','15','','desserts','1'),
('Vanilla Panna Cotta','15','','desserts','1'),

('Josef Chromy Sparkling N.V. – Relbia TAS','56','12','SparklingWine','0'),
('Holm Oak Sparkling Rose – Rowella , Tamar TAS','58','12','SparklingWine','0'),
('Ironhouse Sparkling White – White Sands, East Coast TAS','56','12','SparklingWine','0'),
('McLean Bay Pinot Rose – Bicheno, East Coast TAS','56','12','SparklingWine','0'),

('Milton Pinot Gris – Swansea, East Coast TAS','56','12','WhiteWine','0'),
('Milton Riesling –Swansea, East Coast TAS','56','12','WhiteWine','0'),
('Cape Bernier Haphazard Pinot Gris – East Coast TAS','54','12','WhiteWine','0'),
('Josef Chromy Pinot Gris – Relbia TAS','56','12','WhiteWine','0'),
('Derwent Estate Sauvignon Blanc – Hobart TAS','52','12','WhiteWine','0'),
('Freycinet Wineglass Bay Sauvignon Blanc – East Coast TAS','58','12','WhiteWine','0'),
('Freycinet Louis Chardonnay – Bicheno, East Coast TAS','61','','WhiteWine','0'),
('Ironhouse Chardonnay - White Sands, East Coast TAS','56','12','WhiteWine','0'),
('Apsley Gorge Chardonnay – Bicheno, East Coast TAS','125','','WhiteWine','0'),
('Freycinet Louis Schonburger Riesling – Bicheno, East Coast TAS','54','','WhiteWine','0'),
('Frogmore Creek 2118 FGR Riesling – Cambridge TAS','54','12','WhiteWine','0'),
('Margaret Pooley Tribute Riesling –Richmond TAS','115','12','WhiteWine','0'),
('The Bend Great Oyster Bay Riesling –Cranbrook East Coast TAS','68','','WhiteWine','0'),

('McLean Bay Pinot Noir –Bicheno, East Coast TAS','56','12','RedWine','0'),
('Freycinet Louis Pinot Noir –Bicheno, East Coast TAS','74','','RedWine','0'),
('Freycinet Cabernet Merlot –Bicheno, East Coast TAS','74','','RedWine','0'),
('Apsley Gorge Pinot Noir –Bicheno, East Coast TAS','125','','RedWine','0'),
('The Bend Cabernet Sauvignon –Cranbrook, East Coast TAS','72','','RedWine','0'),
('Storm Bay Cabernet Merlot – Richmond TAS','56','12','RedWine','0'),
('Pooleys Cooinda Vale Pinot Noir –Richmond TAS','115','','RedWine','0'),
('Tim Smith Bugalugs Shiraz –Barossa Valley SA','54','12','RedWine','0'),

('Tassie Beer of the Month','12','','Beer','0'),
('James Boags Premium –Launceston','9','','Beer','0'),
('James Boags xxx –Launceston','9','','Beer','0'),
('Cascade Draught –Hobart','9','','Beer','0'),
('Cascade Premium Light –Hobart','8','','Beer','0'),
('Great Northern Mid Strength – QLD','8.5','','Beer','0'),
('Carlton Dry –VIC','9','','Beer','0'),
('Corona –Mexico','11','','Beer','0'),
('Ironhouse Alc. Ginger Beer','12','','Beer','0'),

('Tassie Apple Cider','12','','Cider','0')